--ZAD1
SELECT MIN(ROUND(CENA_NETTO+(CENA_NETTO*VAT)/100,2)) AS "min",
    MAX(ROUND(CENA_NETTO+(CENA_NETTO*VAT)/100,2)) AS "max"
FROM PRODUKTY;
----
--ZAD2
SELECT ID_ZAMOWIENIA, SUM(ILE)
FROM PRODUKTY_ZAMOWIENIA
GROUP BY ID_ZAMOWIENIA
ORDER BY 1,2;
----
--ZAD3
SELECT PRODUKT
FROM PRODUKTY_ZAMOWIENIA
GROUP BY PRODUKT
HAVING SUM(ILE)>=40;
----
--ZAD4
SELECT KATEGORIA, ROUND(AVG(WAGA),2)
FROM PRODUKTY
GROUP BY KATEGORIA
HAVING COUNT(*)>=2
ORDER BY 2 DESC, 1;  
----
--ZAD5
SELECT KATEGORIA, MIN(CENA_NETTO),
    MAX(CENA_NETTO),
    MAX(CENA_NETTO) - MIN(CENA_NETTO) 
FROM PRODUKTY
GROUP BY KATEGORIA
ORDER BY 1,2;
----
--ZAD6
SELECT KATEGORIA, COUNT(NULLIF(VAT,18)) AS "liczba produktów"
FROM PRODUKTY
GROUP BY KATEGORIA
ORDER BY 1,2;
----
--ZAD7
SELECT COUNT(*)
FROM PRODUKTY
WHERE WAGA<1000;
----
--ZAD8
SELECT SUM(CENA_NETTO)
FROM PRODUKTY
HAVING MAX(CENA_NETTO)>=300;
----
--ZAD9
SELECT 
    CASE
        WHEN COUNT(ADRES_DOSTAWY) = COUNT(DISTINCT ADRES_DOSTAWY) THEN 'TAK'
    ELSE
        'NIE'
    END
FROM ZAMOWIENIA;
----
--ZAD10
SELECT ID_KLIENTA 
FROM ZAMOWIENIA
GROUP BY ID_KLIENTA
HAVING COUNT(*)>1
ORDER BY 1;
----
--ZAD11
SELECT KATEGORIA
FROM PRODUKTY
GROUP BY KATEGORIA
HAVING COUNT(RABAT) = COUNT(COALESCE(RABAT, 0))
ORDER BY 1;
----
--ZAD12
SELECT KATEGORIA
FROM PRODUKTY
WHERE VAT = 8
GROUP BY KATEGORIA
HAVING COUNT(RABAT) = COUNT(COALESCE(RABAT, 0))
ORDER BY 1;
----
--ZAD13
SELECT KATEGORIA AS "kategoria",
    COALESCE(ROUND(VAR_SAMP(CENA_NETTO),2),0.00) AS "wariancja", 
    COALESCE(ROUND(STDDEV_SAMP(CENA_NETTO),2),0.00) AS "odchylenie standardowe"
FROM PRODUKTY
GROUP BY KATEGORIA
ORDER BY 1,2,3;
----
--ZAD14
SELECT COUNT(*)
FROM PRODUKTY
WHERE KATEGORIA = 'Artykuły piśmiennicze';
----
--ZAD15a
SELECT ARRAY_AGG(NUMER_TELEFONU) AS "lista telefonów"
FROM KLIENCI
WHERE NUMER_TELEFONU IS NOT NULL;
----
--ZAD15b
SELECT ARRAY_AGG(NUMER_TELEFONU ORDER BY NUMER_TELEFONU) AS "lista telefonów"
FROM KLIENCI
WHERE NUMER_TELEFONU IS NOT NULL;
----
--ZAD16
SELECT PRODUKT, COUNT(ID_ZAMOWIENIA)
FROM PRODUKTY_ZAMOWIENIA
GROUP BY PRODUKT
ORDER BY 2 DESC, 1;
----
--ZAD17
SELECT 
CASE
    WHEN NIP IS NULL THEN 'Brak'
ELSE
    'Podany'
END AS "NIP",
COUNT(*) AS "liczba klientów"
FROM KLIENCI
GROUP BY NIP IS NULL
ORDER BY 1,2;
----
--ZAD18
SELECT COUNT(EMAIL)
FROM KLIENCI
WHERE EMAIL LIKE '%@onet.eu';
----
--ZAD19
SELECT TO_CHAR(DATA_ZLOZENIA, 'Month') AS "miesiąc",
    COUNT(*) AS "liczba zamówień"
FROM ZAMOWIENIA
GROUP BY TO_CHAR(DATA_ZLOZENIA, 'Month')
ORDER BY 1,2;
----

