--ZAD1
SELECT ID_EGZEMPLARZA,
       TYTUL
FROM EGZEMPLARZE E
    JOIN KSIAZKI K
        ON E.ID_KSIAZKI = K.ID_KSIAZKI
WHERE AUTOR = 'J.R.R. Tolkien'
ORDER BY 1,2;
----
--ZAD2
SELECT NAZWA,
    COUNT(*)
    FROM KATEGORIE KAT
     JOIN KSIAZKI K ON K.ID_KATEGORII = KAT.ID_KATEGORII
GROUP BY NAZWA
ORDER BY 1,2; 
----
--ZAD3
SELECT DISTINCT TYTUL, AUTOR
FROM KSIAZKI K
    NATURAL JOIN EGZEMPLARZE E
    NATURAL JOIN WYPOZYCZENIA W
WHERE DATA_ODDANIA IS NULL;
----
--ZAD4
SELECT AUTOR,
 SUM(CASE
        WHEN ID_EGZEMPLARZA IS NULL THEN 0 
        ELSE 1 
    END) AS "liczba egzemplarzy"
FROM KSIAZKI K LEFT JOIN EGZEMPLARZE E ON K.ID_KSIAZKI = E.ID_KSIAZKI
GROUP BY AUTOR
ORDER BY 1,2;
----
--ZAD5
SELECT C1.IMIE, C1.NAZWISKO, C2.IMIE, C2.NAZWISKO, C1.MIASTO
FROM CZYTELNICY C1
JOIN CZYTELNICY C2
ON C1.ID_CZYTELNIKA<C2.ID_CZYTELNIKA AND C1.MIASTO = C2.MIASTO
ORDER BY 1,2,3,4,5;
----
--ZAD6
SELECT 
K.ID_KSIAZKI,
K.TYTUL,
CASE
WHEN COUNT(DISTINCT E.ID_EGZEMPLARZA)=
COUNT(
    CASE
        WHEN DATA_ODDANIA IS NULL AND W.ID_WYPOZYCZENIA IS NOT NULL THEN 1
        ELSE NULL 
    END
)
THEN FALSE
ELSE TRUE
END
FROM KSIAZKI K
LEFT JOIN EGZEMPLARZE E ON K.ID_KSIAZKI = E.ID_KSIAZKI
LEFT JOIN WYPOZYCZENIA W ON E.ID_EGZEMPLARZA = W.ID_EGZEMPLARZA
GROUP BY K.ID_KSIAZKI
ORDER BY 1,2,3;
----
--ZAD7
SELECT C.IMIE,
C.NAZWISKO,
COUNT(W.ID_WYPOZYCZENIA)
FROM CZYTELNICY C JOIN WYPOZYCZENIA W ON C.ID_CZYTELNIKA = W.ID_CZYTELNIKA
GROUP BY C.ID_CZYTELNIKA
HAVING SUM(CASE WHEN DATA_ODDANIA IS NULL THEN 0 ELSE 1 END) < COUNT(W.ID_WYPOZYCZENIA)
ORDER BY 1,2,3;
----
--ZAD8
SELECT  IMIE, NAZWISKO
FROM CZYTELNICY C JOIN WYPOZYCZENIA W ON C.ID_CZYTELNIKA = W.ID_CZYTELNIKA
WHERE (DATA_ODDANIA IS NOT NULL AND DATA_ODDANIA>OCZEKIWANA_DATA_ODDANIA) 
OR (DATA_ODDANIA IS NULL AND NOW() > OCZEKIWANA_DATA_ODDANIA)
GROUP BY C.ID_CZYTELNIKA, IMIE, NAZWISKO
ORDER BY 1,2;
----
--ZAD9
SELECT C.ID_CZYTELNIKA, IMIE, NAZWISKO, W.ID_WYPOZYCZENIA
FROM CZYTELNICY C JOIN WYPOZYCZENIA W ON C.ID_CZYTELNIKA = W.ID_CZYTELNIKA
WHERE W.ID_WYPOZYCZENIA & ID_WYPOZYCZENIA-1 = 0
ORDER BY 1,2,3,4;
----
--ZAD10
SELECT NAZWA
FROM KATEGORIE KAT
JOIN KSIAZKI K ON KAT.ID_KATEGORII = K.ID_KATEGORII
JOIN EGZEMPLARZE E ON K.ID_KSIAZKI = E.ID_KSIAZKI
JOIN WYPOZYCZENIA W ON E.ID_EGZEMPLARZA = W.ID_EGZEMPLARZA
GROUP BY KAT.ID_KATEGORII
ORDER BY COUNT(ID_WYPOZYCZENIA) DESC, KAT.ID_KATEGORII
LIMIT 1
----
--ZAD11
SELECT TYTUL, AUTOR, COUNT(ID_WYPOZYCZENIA)
FROM KSIAZKI K
JOIN EGZEMPLARZE E ON K.ID_KSIAZKI = E.ID_KSIAZKI
JOIN WYPOZYCZENIA W ON E.ID_EGZEMPLARZA = W.ID_EGZEMPLARZA
GROUP BY K.ID_KSIAZKI
ORDER BY 3 DESC,1,2;
----
--ZAD12
SELECT IMIE, NAZWISKO, COALESCE(NAZWA, 'Brak')
FROM CZYTELNICY C
FULL OUTER JOIN CZYTELNIK_ZAINTERESOWANIA CZ ON CZ.ID_CZYTELNIKA = C.ID_CZYTELNIKA
LEFT JOIN KATEGORIE KAT ON CZ.ID_KATEGORII = KAT.ID_KATEGORII
ORDER BY 1,2,3;
----
--ZAD13
SELECT IMIE, NAZWISKO, TYTUL, AUTOR
FROM CZYTELNICY C
JOIN CZYTELNIK_ZAINTERESOWANIA CZ ON C.ID_CZYTELNIKA = CZ.ID_CZYTELNIKA
JOIN KATEGORIE KAT ON CZ.ID_KATEGORII = KAT.ID_KATEGORII
JOIN KSIAZKI K ON KAT.ID_KATEGORII = K.ID_KATEGORII
WHERE NAZWISKO LIKE 'K%'
ORDER BY 1,2,3,4;
----
--ZAD14
SELECT IMIE, NAZWISKO, 
COUNT(W.ID_WYPOZYCZENIA),
CASE
    WHEN COUNT(W.ID_WYPOZYCZENIA)>20 THEN 'mól książkowy'
    ELSE 'niedzielny czytelnik'
END
FROM CZYTELNICY C
JOIN WYPOZYCZENIA W ON C.ID_CZYTELNIKA = W.ID_CZYTELNIKA
WHERE DATA_WYPOZYCZENIA >= '2023-01-01'
GROUP BY C.ID_CZYTELNIKA
HAVING COUNT(W.ID_WYPOZYCZENIA)>=3
ORDER BY 3 DESC, 1, 2;
----
--ZAD15
SELECT DISTINCT C.ID_CZYTELNIKA, 
IMIE, 
NAZWISKO, 
K.ID_KSIAZKI, 
TYTUL,
AUTOR,
CASE
    WHEN COUNT(ID_WYPOZYCZENIA)>0 THEN 'TAK'
    ELSE 'NIE'
END AS "wypożyczona"
FROM CZYTELNICY C
CROSS JOIN KSIAZKI K
LEFT JOIN EGZEMPLARZE E ON K.ID_KSIAZKI = E.ID_KSIAZKI
LEFT JOIN WYPOZYCZENIA W ON W.ID_EGZEMPLARZA = E.ID_EGZEMPLARZA 
AND C.ID_CZYTELNIKA = W.ID_CZYTELNIKA
GROUP BY 
    C.ID_CZYTELNIKA, 
    C.IMIE, 
    C.NAZWISKO, 
    K.ID_KSIAZKI, 
    K.TYTUL,
    K.AUTOR
ORDER BY 1;
----
--ZAD16
SELECT IMIE AS "imię", NAZWISKO,
COUNT(DISTINCT
    CASE
        WHEN ID_WYPOZYCZENIA IS NULL THEN NULL
        WHEN K.ID_KATEGORII IS NULL THEN -1
        ELSE K.ID_KATEGORII
    END
) AS "liczba różnych kategorii"
FROM CZYTELNICY C
LEFT JOIN WYPOZYCZENIA W ON C.ID_CZYTELNIKA = W.ID_CZYTELNIKA
LEFT JOIN EGZEMPLARZE E ON W.ID_EGZEMPLARZA = E.ID_EGZEMPLARZA
LEFT JOIN KSIAZKI K ON E.ID_KSIAZKI = K.ID_KSIAZKI
LEFT JOIN KATEGORIE KAT ON K.ID_KATEGORII = KAT.ID_KATEGORII
GROUP BY C.ID_CZYTELNIKA
ORDER BY 1,2,3;
----