--ZAD1
SELECT * 
FROM kierowcy
ORDER BY 1;
----
--ZAD2
SELECT * 
FROM wykroczenia
ORDER BY kwota, nazwa;
----
--ZAD3
SELECT IMIE, NAZWISKO
FROM KIEROWCY
ORDER BY 1,2;
----
--ZAD4
SELECT DISTINCT IMIE, NAZWISKO
FROM KIEROWCY
ORDER BY NAZWISKO, IMIE DESC;
----
--ZAD5
SELECT IMIE, NAZWISKO, WYNAGRODZENIE*12
FROM STRAZNICY
ORDER BY 1,2,3;
----
--ZAD6
SELECT IMIE, NAZWISKO, (WYNAGRODZENIE+COALESCE(PREMIA,0))*12
FROM STRAZNICY
ORDER BY 1,2,3;
----
--ZAD7
SELECT *
FROM STRAZNICY
WHERE WYNAGRODZENIE>=6000 AND WYNAGRODZENIE<=8000
ORDER BY 1;
----
--ZAD8
SELECT *
FROM STRAZNICY
WHERE WYNAGRODZENIE>6000 AND ID_PRZELOZONEGO IS NOT NULL
ORDER BY 1;
----
--ZAD9
SELECT *
FROM WYKROCZENIA 
WHERE COALESCE(PUNKTY,0) <= 10
ORDER BY 1;
----
--ZAD10
SELECT *
FROM KIEROWCY
WHERE EXTRACT(YEAR FROM DATA_OD)>2000
ORDER BY 1;
----
--ZAD11
SELECT *
FROM WYKROCZENIA
WHERE NAZWA LIKE '%Przekroczenie prędkości%'
ORDER BY 1;
----
--ZAD12
SELECT *
FROM KIEROWCY
WHERE ADRES LIKE '%Grudziądz%' AND DATA_DO IS NULL
ORDER BY 1;
----
--ZAD13
SELECT IMIE, NAZWISKO, ADRES
FROM KIEROWCY
WHERE DATA_OD<= '01-01-2012' AND (DATA_DO >= '01-01-2012' OR DATA_DO IS NULL)
ORDER BY 1,2,3;
----
--ZAD14
SELECT IMIE || ' ' || LEFT(NAZWISKO,1) || '.' AS "kierowca_bez_uprawnien"
FROM KIEROWCY
WHERE DATA_DO < CURRENT_DATE
ORDER BY 1;
----
--ZAD15
SELECT NAZWISKO || ' pracuje jako ' || LOWER(STANOWISKO) || ' i zarabia ' || WYNAGRODZENIE AS "STRAŻNICY MIEJSCY"
FROM STRAZNICY
ORDER BY WYNAGRODZENIE DESC;
----
--ZAD16
SELECT NAZWISKO, ROUND(WYNAGRODZENIE*1.15) 
FROM STRAZNICY;
----
--ZAD17
SELECT NAZWISKO || REPEAT('.', (40 - LENGTH(NAZWISKO) - LENGTH(STANOWISKO))) || UPPER(STANOWISKO) AS "nazwisko i stanowisko"
FROM STRAZNICY
ORDER BY ID;
----
--ZAD18
SELECT 
    UPPER(LEFT(STANOWISKO,2)) || ID AS "wygenerowany kod", 
    ID AS "id strażnika", 
    NAZWISKO AS "nazwisko",
    STANOWISKO AS "stanowisko"
FROM STRAZNICY
ORDER BY 1,2,3,4; 
----
--ZAD19
SELECT NAZWISKO, REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NAZWISKO, 'K', 'X'), 'k', 'X'), 'L', 'X'), 'l', 'X'), 'M', 'X'), 'm', 'X') AS "zmienione nazwisko"
FROM STRAZNICY
ORDER BY 1,2;
----
--ZAD20
SELECT 
    IMIE || ' ' || NAZWISKO AS "imię i nazwisko",
    TO_CHAR(DATA_OD, 'Month') || ' , ' || TO_CHAR(DATA_OD,'DD') || ' ' || EXTRACT(YEAR FROM DATA_OD) AS "uzyskanie uprawnień"
FROM KIEROWCY
WHERE EXTRACT(YEAR FROM AGE(DATA_DO, DATA_OD)) < 5 AND DATA_DO IS NOT NULL
ORDER BY AGE(DATA_DO, DATA_OD);
----
--ZAD21
SELECT ID,
    CASE
        WHEN KWOTA>400 THEN 'więcej'
        WHEN KWOTA=400 THEN 'równa'
    ELSE
        'mniej'
    END
FROM WYKROCZENIA
ORDER BY 1,2;
----
--ZAD22
SELECT IMIE, NAZWISKO, PREMIA
FROM STRAZNICY
ORDER BY COALESCE(PREMIA, 0) DESC, ID; 
----
--ZAD23
SELECT *
FROM STRAZNICY
ORDER BY 
    CASE
        WHEN SUBSTRING(PESEL FROM 3 FOR 1) = '2' THEN MAKE_DATE(('20'||LEFT(PESEL,2))::INT,  SUBSTRING(PESEL FROM 4 FOR 1)::INT, SUBSTRING(PESEL FROM 5 FOR 2)::INT)
        WHEN SUBSTRING(PESEL FROM 3 FOR 1) = '3' THEN MAKE_DATE(('20'||LEFT(PESEL,2))::INT,  ('1'||SUBSTRING(PESEL FROM 4 FOR 1))::INT, SUBSTRING(PESEL FROM 5 FOR 2)::INT)
    ELSE
        MAKE_DATE(('19'||LEFT(PESEL,2))::INT, SUBSTRING(PESEL FROM 3 FOR 2)::INT, SUBSTRING(PESEL FROM 5 FOR 2)::INT)
    END
LIMIT 5;
----
--ZAD24
SELECT IMIE, NAZWISKO, PESEL
FROM KIEROWCY
INTERSECT
SELECT IMIE, NAZWISKO, PESEL
FROM STRAZNICY;
----